name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choix de l'environnement"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest

    env:
      TF_VERSION: 1.6.6
      ENV: ${{ github.event.inputs.environment }}
      TF_BACKEND_BUCKET: terraform-state-boubaker-besson
      TF_BACKEND_PREFIX_DEV: dev/terraform/state
      TF_BACKEND_PREFIX_PROD: prod/terraform/state

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Auth GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Terraform Init (backend prefix par env)
        run: |
          PREFIX=$([ "$ENV" = "dev" ] && echo "$TF_BACKEND_PREFIX_DEV" || echo "$TF_BACKEND_PREFIX_PROD")
          terraform init \
            -backend-config="bucket=$TF_BACKEND_BUCKET" \
            -backend-config="prefix=$PREFIX"
        working-directory: Terraform-BOUBAKER-BESSON

      - name: Terraform Destroy
        run: |
          terraform destroy \
            -var-file="envs/$ENV/terraform.tfvars" \
            -auto-approve
        working-directory: Terraform-BOUBAKER-BESSON
